---
# Configuration file for MegaLinter

APPLY_FIXES: all # Auto-fix all issues

# ENABLE:         # Uncomment and list to enable specific categories
# ENABLE_LINTERS: # Uncomment and list to enable specific linters

# DISABLE:
#   - COPYPASTE   # Disable checks of excessive copy-pastes
#   - SPELL       # Disable checks of spelling mistakes

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true
JSON_REPORTER: true
UPDATED_SOURCES_REPORTER: true

DISABLE_ERRORS: false

OUTPUT_FORMAT: text
REPORT_OUTPUT_FOLDER: reports

ENABLE_ALL_LINTERS: false
ENABLE:
  - JAVASCRIPT_ES
  - PYTHON_PYLINT
  - YAML
  - DOCKERFILE_HADOLINT

JAVASCRIPT_ES_FILTER_REGEX_INCLUDE: '(src|test)/'
PYTHON_PYLINT_FILTER_REGEX_INCLUDE: '*.py'
