# MegaLinter configuration for a JavaScript/TypeScript project using Jenkins

VALIDATE_ALL_CODEBASE: true

ENABLE_LINTERS:
  - ESLINT
  - PRETTIER
  - SPELL
  - JSCPD

APPLY_FIXES: all

UPLOAD_REPORTS_TO_FILEIO: true

SHOW_ELAPSED_TIME: true

GIT_MAIN_BRANCH: main

# ESLINT_CONFIG_FILE: .eslintrc.js
# PRETTIER_CONFIG_FILE: .prettierrc
# EXCLUDED_DIRECTORIES: node_modules,build,dist
